<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150720/1-150H01P123.jpg ",93,237);
$z[1][4]['ddimg']="/uploads/allimg/150720/1-150H01P123.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1017";
$z[1][4]['height']="586";
$z[2]=Array("img"," /uploads/allimg/150720/1-150H01P129.jpg ",239,384);
$z[2][4]['ddimg']="/uploads/allimg/150720/1-150H01P129.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1600";
$z[2][4]['height']="1063";
$z[3]=Array("img"," /uploads/allimg/150720/1-150H01P135.jpg ",386,529);
$z[3][4]['ddimg']="/uploads/allimg/150720/1-150H01P135.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="330";
$z[3][4]['height']="220";
$z[4]=Array("img"," /uploads/allimg/150720/1-150H01P139.jpg ",531,674);
$z[4][4]['ddimg']="/uploads/allimg/150720/1-150H01P139.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="352";
$z[4][4]['height']="220";
$z[5]=Array("img"," /uploads/allimg/150720/1-150H01P148.jpg ",676,821);
$z[5][4]['ddimg']="/uploads/allimg/150720/1-150H01P148.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="1600";
$z[5][4]['height']="1063";

?>