{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/150718/1-150GR03053.jpg' text='' width='1600' height='1200'} /uploads/allimg/150718/1-150GR03053.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR03056.jpg' text='' width='1024' height='683'} /uploads/allimg/150718/1-150GR03056.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR03059.jpg' text='' width='1024' height='683'} /uploads/allimg/150718/1-150GR03059.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR03102.jpg' text='' width='1012' height='615'} /uploads/allimg/150718/1-150GR03102.jpg {/dede:img}
