{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/150720/1-150H01TI6.jpg' text='' width='900' height='600'} /uploads/allimg/150720/1-150H01TI6.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150720/1-150H01TJ0.jpg' text='' width='998' height='665'} /uploads/allimg/150720/1-150H01TJ0.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150720/1-150H01TJ4.jpg' text='' width='1024' height='720'} /uploads/allimg/150720/1-150H01TJ4.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150720/1-150H01TJ8.jpg' text='' width='960' height='720'} /uploads/allimg/150720/1-150H01TJ8.jpg {/dede:img}
