<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150720/1-150H01TI6.jpg ",93,234);
$z[1][4]['ddimg']="/uploads/allimg/150720/1-150H01TI6.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="900";
$z[1][4]['height']="600";
$z[2]=Array("img"," /uploads/allimg/150720/1-150H01TJ0.jpg ",236,377);
$z[2][4]['ddimg']="/uploads/allimg/150720/1-150H01TJ0.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="998";
$z[2][4]['height']="665";
$z[3]=Array("img"," /uploads/allimg/150720/1-150H01TJ4.jpg ",379,521);
$z[3][4]['ddimg']="/uploads/allimg/150720/1-150H01TJ4.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1024";
$z[3][4]['height']="720";
$z[4]=Array("img"," /uploads/allimg/150720/1-150H01TJ8.jpg ",523,664);
$z[4][4]['ddimg']="/uploads/allimg/150720/1-150H01TJ8.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="960";
$z[4][4]['height']="720";

?>