<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150720/1-150H01U341.jpg ",93,237);
$z[1][4]['ddimg']="/uploads/allimg/150720/1-150H01U341.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1024";
$z[1][4]['height']="683";
$z[2]=Array("img"," /uploads/allimg/150720/1-150H01U346.jpg ",239,383);
$z[2][4]['ddimg']="/uploads/allimg/150720/1-150H01U346.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1024";
$z[2][4]['height']="576";
$z[3]=Array("img"," /uploads/allimg/150720/1-150H01U351.jpg ",385,529);
$z[3][4]['ddimg']="/uploads/allimg/150720/1-150H01U351.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1024";
$z[3][4]['height']="680";

?>