<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150720/1-150H0132643.jpg ",93,240);
$z[1][4]['ddimg']="/uploads/allimg/150720/1-150H0132643.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1800";
$z[1][4]['height']="1196";
$z[2]=Array("img"," /uploads/allimg/150720/1-150H0132A0.jpg ",242,386);
$z[2][4]['ddimg']="/uploads/allimg/150720/1-150H0132A0.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1300";
$z[2][4]['height']="863";
$z[3]=Array("img"," /uploads/allimg/150720/1-150H0132A5.jpg ",388,532);
$z[3][4]['ddimg']="/uploads/allimg/150720/1-150H0132A5.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1050";
$z[3][4]['height']="631";

?>