{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/150718/1-150GR02053.jpg' text='' width='1024' height='683'} /uploads/allimg/150718/1-150GR02053.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR02058.jpg' text='' width='690' height='461'} /uploads/allimg/150718/1-150GR02058.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR02102.jpg' text='' width='1280' height='800'} /uploads/allimg/150718/1-150GR02102.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR02105.jpg' text='' width='315' height='220'} /uploads/allimg/150718/1-150GR02105.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR02137.jpg' text='' width='1920' height='1200'} /uploads/allimg/150718/1-150GR02137.jpg {/dede:img}
