<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150720/1-150H01U106.jpg ",93,237);
$z[1][4]['ddimg']="/uploads/allimg/150720/1-150H01U106.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1024";
$z[1][4]['height']="717";
$z[2]=Array("img"," /uploads/allimg/150720/1-150H01U110.jpg ",239,383);
$z[2][4]['ddimg']="/uploads/allimg/150720/1-150H01U110.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1024";
$z[2][4]['height']="868";
$z[3]=Array("img"," /uploads/allimg/150720/1-150H01U115.jpg ",385,529);
$z[3][4]['ddimg']="/uploads/allimg/150720/1-150H01U115.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1100";
$z[3][4]['height']="726";
$z[4]=Array("img"," /uploads/allimg/150720/1-150H01U120.jpg ",531,675);
$z[4][4]['ddimg']="/uploads/allimg/150720/1-150H01U120.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1100";
$z[4][4]['height']="732";

?>