<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150720/1-150H01K915.jpg ",93,237);
$z[1][4]['ddimg']="/uploads/allimg/150720/1-150H01K915.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1024";
$z[1][4]['height']="739";
$z[2]=Array("img"," /uploads/allimg/150720/1-150H01K920.jpg ",239,382);
$z[2][4]['ddimg']="/uploads/allimg/150720/1-150H01K920.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="999";
$z[2][4]['height']="816";
$z[3]=Array("img"," /uploads/allimg/150720/1-150H01K924.jpg ",384,528);
$z[3][4]['ddimg']="/uploads/allimg/150720/1-150H01K924.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1440";
$z[3][4]['height']="900";
$z[4]=Array("img"," /uploads/allimg/150720/1-150H01K932.jpg ",530,673);
$z[4][4]['ddimg']="/uploads/allimg/150720/1-150H01K932.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="900";
$z[4][4]['height']="600";

?>