{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/150720/1-150H01K915.jpg' text='' width='1024' height='739'} /uploads/allimg/150720/1-150H01K915.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150720/1-150H01K920.jpg' text='' width='999' height='816'} /uploads/allimg/150720/1-150H01K920.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150720/1-150H01K924.jpg' text='' width='1440' height='900'} /uploads/allimg/150720/1-150H01K924.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150720/1-150H01K932.jpg' text='' width='900' height='600'} /uploads/allimg/150720/1-150H01K932.jpg {/dede:img}
