{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150718/1-150GR02531.jpg' text='' width='1000' height='666'} /uploads/allimg/150718/1-150GR02531.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR02534.jpg' text='' width='1024' height='1024'} /uploads/allimg/150718/1-150GR02534.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR02537.jpg' text='' width='1024' height='683'} /uploads/allimg/150718/1-150GR02537.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR02540.jpg' text='' width='1024' height='683'} /uploads/allimg/150718/1-150GR02540.jpg {/dede:img}
