<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150720/1-150H0135355.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/150720/1-150H0135355.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="858";
$z[1][4]['height']="570";
$z[2]=Array("img"," /uploads/allimg/150720/1-150H0135404.jpg ",240,386);
$z[2][4]['ddimg']="/uploads/allimg/150720/1-150H0135404.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1000";
$z[2][4]['height']="669";
$z[3]=Array("img"," /uploads/allimg/150720/1-150H0135415.jpg ",388,535);
$z[3][4]['ddimg']="/uploads/allimg/150720/1-150H0135415.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1530";
$z[3][4]['height']="1147";

?>