<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150720/1-150H0122247.jpg ",93,239);
$z[1][4]['ddimg']="/uploads/allimg/150720/1-150H0122247.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1024";
$z[1][4]['height']="683";
$z[2]=Array("img"," /uploads/allimg/150720/1-150H0122251.jpg ",241,386);
$z[2][4]['ddimg']="/uploads/allimg/150720/1-150H0122251.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="690";
$z[2][4]['height']="461";
$z[3]=Array("img"," /uploads/allimg/150720/1-150H0122255.jpg ",388,534);
$z[3][4]['ddimg']="/uploads/allimg/150720/1-150H0122255.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1280";
$z[3][4]['height']="800";
$z[4]=Array("img"," /uploads/allimg/150720/1-150H0122259.jpg ",536,681);
$z[4][4]['ddimg']="/uploads/allimg/150720/1-150H0122259.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="315";
$z[4][4]['height']="220";

?>