<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150719/1-150G9192I0.gif ",93,236);
$z[1][4]['ddimg']="/uploads/allimg/150719/1-150G9192I0.gif";
$z[1][4]['text']="";
$z[1][4]['width']="290";
$z[1][4]['height']="211";
$z[2]=Array("img"," /uploads/allimg/150719/1-150G9192I3.gif ",238,381);
$z[2][4]['ddimg']="/uploads/allimg/150719/1-150G9192I3.gif";
$z[2][4]['text']="";
$z[2][4]['width']="290";
$z[2][4]['height']="211";
$z[3]=Array("img"," /uploads/allimg/150719/1-150G9192I6.gif ",383,526);
$z[3][4]['ddimg']="/uploads/allimg/150719/1-150G9192I6.gif";
$z[3][4]['text']="";
$z[3][4]['width']="290";
$z[3][4]['height']="211";
$z[4]=Array("img"," /uploads/allimg/150719/1-150G9192J0.jpg ",528,671);
$z[4][4]['ddimg']="/uploads/allimg/150719/1-150G9192J0.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="425";
$z[4][4]['height']="425";

?>