{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/150719/1-150G9192I0.gif' text='' width='290' height='211'} /uploads/allimg/150719/1-150G9192I0.gif {/dede:img}
{dede:img ddimg='/uploads/allimg/150719/1-150G9192I3.gif' text='' width='290' height='211'} /uploads/allimg/150719/1-150G9192I3.gif {/dede:img}
{dede:img ddimg='/uploads/allimg/150719/1-150G9192I6.gif' text='' width='290' height='211'} /uploads/allimg/150719/1-150G9192I6.gif {/dede:img}
{dede:img ddimg='/uploads/allimg/150719/1-150G9192J0.jpg' text='' width='425' height='425'} /uploads/allimg/150719/1-150G9192J0.jpg {/dede:img}
