<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:diqu itemname="地区" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="亚洲,欧洲,北美洲,南美洲,大洋洲,非洲,南极"  maxlength="250" page="">
</field:diqu>

<field:leixing itemname="类型" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="私人指定,跟团游,自由行,蜜月"  maxlength="250" page="">
</field:leixing>
