<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150720/1-150H0133R3.jpg ",93,237);
$z[1][4]['ddimg']="/uploads/allimg/150720/1-150H0133R3.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1024";
$z[1][4]['height']="768";
$z[2]=Array("img"," /uploads/allimg/150720/1-150H0133S1.jpg ",239,384);
$z[2][4]['ddimg']="/uploads/allimg/150720/1-150H0133S1.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1500";
$z[2][4]['height']="1130";
$z[3]=Array("img"," /uploads/allimg/150720/1-150H0133S8.jpg ",386,530);
$z[3][4]['ddimg']="/uploads/allimg/150720/1-150H0133S8.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1024";
$z[3][4]['height']="679";
$z[4]=Array("img"," /uploads/allimg/150720/1-150H0133T5.jpg ",532,676);
$z[4][4]['ddimg']="/uploads/allimg/150720/1-150H0133T5.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1024";
$z[4][4]['height']="683";

?>