<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150718/1-150GR00S5.jpg ",93,235);
$z[1][4]['ddimg']="/uploads/allimg/150718/1-150GR00S5.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1070";
$z[1][4]['height']="720";
$z[2]=Array("img"," /uploads/allimg/150718/1-150GR00S8.jpg ",237,379);
$z[2][4]['ddimg']="/uploads/allimg/150718/1-150GR00S8.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1440";
$z[2][4]['height']="900";
$z[3]=Array("img"," /uploads/allimg/150718/1-150GR00T0.jpg ",381,523);
$z[3][4]['ddimg']="/uploads/allimg/150718/1-150GR00T0.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1024";
$z[3][4]['height']="683";
$z[4]=Array("img"," /uploads/allimg/150718/1-150GR00T4.jpg ",525,667);
$z[4][4]['ddimg']="/uploads/allimg/150718/1-150GR00T4.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1024";
$z[4][4]['height']="678";

?>