{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150718/1-150GR00S5.jpg' text='' width='1070' height='720'} /uploads/allimg/150718/1-150GR00S5.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR00S8.jpg' text='' width='1440' height='900'} /uploads/allimg/150718/1-150GR00S8.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR00T0.jpg' text='' width='1024' height='683'} /uploads/allimg/150718/1-150GR00T0.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR00T4.jpg' text='' width='1024' height='678'} /uploads/allimg/150718/1-150GR00T4.jpg {/dede:img}
