
<field:name itemname="昵称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tell itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tell>

<field:emial itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:emial>

<field:neirong itemname="内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:neirong>
