<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150719/1-150G9192602.jpg ",93,240);
$z[1][4]['ddimg']="/uploads/allimg/150719/1-150G9192602.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1600";
$z[1][4]['height']="1200";
$z[2]=Array("img"," /uploads/allimg/150719/1-150G9192606.jpg ",242,388);
$z[2][4]['ddimg']="/uploads/allimg/150719/1-150G9192606.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1024";
$z[2][4]['height']="683";
$z[3]=Array("img"," /uploads/allimg/150719/1-150G9192609.jpg ",390,536);
$z[3][4]['ddimg']="/uploads/allimg/150719/1-150G9192609.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1024";
$z[3][4]['height']="683";
$z[4]=Array("img"," /uploads/allimg/150719/1-150G9192614.jpg ",538,684);
$z[4][4]['ddimg']="/uploads/allimg/150719/1-150G9192614.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1012";
$z[4][4]['height']="615";
$z[5]=Array("img"," /uploads/allimg/150719/1-150G9192618.jpg ",686,832);
$z[5][4]['ddimg']="/uploads/allimg/150719/1-150G9192618.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="1024";
$z[5][4]['height']="683";

?>