<?php
$z[0]=Array("field","",331,350);
$z[0][4]['name']="title";
$z[1]=Array("global","",351,377);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",801,836);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",934,956);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1099,1117);
$z[4][4]['name']="body";
$z[5]=Array("productimagelist","\r\n	<img alt=\"\" src=\"[field:imgsrc/]\" style=\"width: 800px\" /><br /><br />\r\n	",1131,1253);
$z[6]=Array("include","",1284,1321);
$z[6][4]['filename']="footer.htm";

?>