{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/150718/1-150GR01513.jpg' text='' width='1200' height='750'} /uploads/allimg/150718/1-150GR01513.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR01516.jpg' text='' width='1600' height='898'} /uploads/allimg/150718/1-150GR01516.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR01520.jpg' text='' width='1024' height='682'} /uploads/allimg/150718/1-150GR01520.jpg {/dede:img}
