<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150720/1-150H01P338.jpg ",93,236);
$z[1][4]['ddimg']="/uploads/allimg/150720/1-150H01P338.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="858";
$z[1][4]['height']="536";
$z[2]=Array("img"," /uploads/allimg/150720/1-150H01P343.jpg ",238,382);
$z[2][4]['ddimg']="/uploads/allimg/150720/1-150H01P343.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1000";
$z[2][4]['height']="750";
$z[3]=Array("img"," /uploads/allimg/150720/1-150H01P349.jpg ",384,528);
$z[3][4]['ddimg']="/uploads/allimg/150720/1-150H01P349.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1014";
$z[3][4]['height']="581";
$z[4]=Array("img"," /uploads/allimg/150720/1-150H01P354.jpg ",530,674);
$z[4][4]['ddimg']="/uploads/allimg/150720/1-150H01P354.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1024";
$z[4][4]['height']="768";

?>