{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/150718/1-150GR00325.jpg' text='' width='1024' height='683'} /uploads/allimg/150718/1-150GR00325.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR00331.jpg' text='' width='1024' height='682'} /uploads/allimg/150718/1-150GR00331.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/150718/1-150GR00335.jpg' text='' width='960' height='600'} /uploads/allimg/150718/1-150GR00335.jpg {/dede:img}
