<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150718/1-150GR00325.jpg ",93,237);
$z[1][4]['ddimg']="/uploads/allimg/150718/1-150GR00325.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1024";
$z[1][4]['height']="683";
$z[2]=Array("img"," /uploads/allimg/150718/1-150GR00331.jpg ",239,383);
$z[2][4]['ddimg']="/uploads/allimg/150718/1-150GR00331.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1024";
$z[2][4]['height']="682";
$z[3]=Array("img"," /uploads/allimg/150718/1-150GR00335.jpg ",385,528);
$z[3][4]['ddimg']="/uploads/allimg/150718/1-150GR00335.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="960";
$z[3][4]['height']="600";

?>