<?php
$z[0]=Array("global","",331,357);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",833,868);
$z[1][4]['filename']="head.htm";
$z[2]=Array("arclist","\r\n					\r\n					<li>\r\n                <div class=\"pro_11\">\r\n                    <img src=\"[field:picname/]\" width=\"100%\" />\r\n                    <a href=\"[field:arcurl /]\">\r\n                        <div class=\"tt\">\r\n                            <div class=\"titles\">[field:title /]</div>\r\n                        </div>\r\n                    </a>\r\n                </div>\r\n            </li>\r\n			",4142,4594);
$z[2][4]['row']="16";
$z[2][4]['typeid']="2";
$z[2][4]['titlelen']="10";
$z[3]=Array("type","<div class=\"sl_1\">[field:typename /]</div>",6343,6419);
$z[3][4]['typeid']="3";
$z[4]=Array("arclist","\r\n						<li>\r\n                            <div class=\"fx_1\">\r\n                                <a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"100%\" /></a>\r\n                                <a href=\"[field:arcurl/]\">\r\n                                    <div class=\"ddd\">\r\n                                        <div class=\"titles\">[field:title /]</div>\r\n                                        <div class=\"acctime\">[field:pubdate function=\"MyDate('d/m/Y',@me)\"/]</div>\r\n                                        <div class=\"info_disc\"></div>\r\n                                    </div>\r\n                                </a>\r\n                            </div>\r\n                        </li>\r\n						",6850,7607);
$z[4][4]['typeid']="3";
$z[4][4]['row']="6";
$z[5]=Array("type","<div class=\"a_1\">[field:typename /]</div>",8129,8204);
$z[5][4]['typeid']="1";
$z[6]=Array("type","<span class=\"news_cn_title\">[field:typename /]</span>",11272,11359);
$z[6][4]['typeid']="4";
$z[7]=Array("arclist","\r\n				<div class=\"d_1\">\r\n                	<div class=\"d1_img\"><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"485\" height=\"280\" class=\"juzhongimg\"/></a><span class=\"juzhongspan\"></span></div>\r\n                	<div class=\"d1_title\"><a href=\"[field:arcurl/]\">[field:title /]</a></div>\r\n                	<div class=\"d1_acctime\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</div>\r\n                	<div class=\"d1_bife\">\r\n                    	[field:infos/]... \r\n                    </div>\r\n                </div>\r\n				",11472,12069);
$z[7][4]['typeid']="4";
$z[7][4]['row']="1";
$z[7][4]['orderby']="pubdate";
$z[8]=Array("arclist","\r\n												    <li>\r\n                                <div class=\"d2_img\"><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"230\" height=\"169\"/></a></div>\r\n                                <div class=\"d2_title\"><a href=\"/info-detail.php?InfoId=79\">[field:title /]</a></div>\r\n                                <div class=\"d2_acctime\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</div>\r\n                            </li>\r\n							",12180,12699);
$z[8][4]['typeid']="4";
$z[8][4]['row']="4";
$z[8][4]['titlelen']="20";
$z[8][4]['orderby']="pubdate";
$z[9]=Array("global","",16806,16832);
$z[9][4]['name']="cfg_powerby";
$z[10]=Array("global","",16834,16858);
$z[10][4]['name']="cfg_beian";

?>