<?php
$z[0]=Array("field","",331,350);
$z[0][4]['name']="title";
$z[1]=Array("global","",351,377);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",799,834);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",927,949);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1080,1101);
$z[4][4]['name']="content";
$z[5]=Array("global","",9147,9173);
$z[5][4]['name']="cfg_powerby";
$z[6]=Array("global","",9175,9199);
$z[6][4]['name']="cfg_beian";

?>