<?php
$z[0]=Array("field","",331,350);
$z[0][4]['name']="title";
$z[1]=Array("global","",351,377);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",799,834);
$z[2][4]['filename']="head.htm";
$z[3]=Array("list","\r\n          <li >\r\n            <div class=\"i_1\">\r\n              <div class=\"pim\"> <a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" class=\"juzhongimg\" /></a><span class=\"juzhongspan\"></span> </div>\r\n            </div>\r\n            <div class=\"inst_title\"> <a href=\"[field:arcurl/]\"> [field:title/] </a> </div>\r\n          </li>\r\n          ",1113,1505);
$z[3][4]['pagesize']="8";
$z[3][4]['titlelen']="20";
$z[4]=Array("pagelist","",1680,1736);
$z[4][4]['listitem']="pre,next,pageno";
$z[4][4]['listsize']="5";
$z[5]=Array("include","",1788,1825);
$z[5][4]['filename']="footer.htm";

?>