<?php
$z[0]=Array("field","",331,350);
$z[0][4]['name']="title";
$z[1]=Array("global","",351,377);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",801,836);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",928,950);
$z[3][4]['name']="typename";
$z[4]=Array("php"," AddFilter(2,1,'diqu'); ",1097,1142);
$z[5]=Array("php"," AddFilter(2,1,'leixing'); ",1273,1321);
$z[6]=Array("list","\r\n											<li >\r\n                            <div class=\"pim\">\r\n                                <div class=\"pimg\">\r\n                                    <a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" class=\"juzhongimg\"/></a><span class=\"juzhongspan\"></span>\r\n                                </div>\r\n                            </div>\r\n                            <div class=\"pro_name\"><a href=\"[field:arcurl/]\">[field:title/]</a></div>\r\n                        </li>\r\n						",2426,2960);
$z[6][4]['pagesize']="9";
$z[6][4]['titlelen']="30";
$z[7]=Array("pagelist","",3129,3185);
$z[7][4]['listitem']="pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",3249,3286);
$z[8][4]['filename']="footer.htm";

?>